apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu
  name: my-ubuntu
spec:
  containers:
  - image: docker.io/shenjuna/my-debug-container:latest
    name: my-ubuntu
    command: ["/bin/bash", "-c"]
    args: ["while true; do echo 'I am alive'; sleep 10; done"]
    env:
    - name: HTTP_PROXY
      value: http://proxy.gtm.lilly.com:9000
    - name: HTTPS_PROXY
      value: http://proxy.gtm.lilly.com:9000
    - name: NO_PROXY
      value: .svc,.cluster.local,127.0.0.1,.lilly.com
  restartPolicy: Always
