apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: my-ubuntu
  name: my-ubuntu
spec:
  containers:
  - image: docker.io/shenjuna/shenjuna:latest
    name: my-ubuntu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
