# postgres-statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
       - name: postgres
         image: postgres:latest
         env:
         - name: HTTP_PROXY
           value: "http://jp-proxy.xh3.lilly.com:9000"
         - name: HTTPS_PROXY
           value: "http://jp-proxy.xh3.lilly.com:9000"
         - name: NO_PROXY
           value: ".lilly.com,.svc.cluster.local,localhost,127.0.0.1"  # Adjust this based on your needs
         - name: POSTGRES_USER
           valueFrom:
             secretKeyRef:
               name: db-credentials
               key: DB_USER
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: db-credentials
               key: DB_PASSWORD
         - name: POSTGRES_DB
           value: "netbox"
         - name: PGDATA
           value: /var/lib/postgresql/data/data/
         volumeMounts:
         - name: postgres-persistent-storage
           mountPath: /var/lib/postgresql/data/
      volumes:
       - name: postgres-persistent-storage
         persistentVolumeClaim:
           claimName: postgresql

