apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  # clusterIP: None  # 注释或移除这一行以使用默认的 ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres  # 与 StatefulSet 的标签匹配
