kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgresql
  labels:
    app: netbox

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: app044-unity-prd
  volumeMode: Filesystem
